wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715200364.841438
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 51
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 51
      - 53
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.12.2
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: temperature
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
